import { THREE_BLEND_MODE } from '../blend.js';

enum M2_MATERIAL_PASS {
  PASS_0 = 0,
  PASS_1,
  PASS_COUNT,
}

const M2_MATERIAL_TO_THREE_BLEND_MODE = {
  [M2_MATERIAL_PASS.PASS_0]: [
    THREE_BLEND_MODE.BLEND_OPAQUE,
    THREE_BLEND_MODE.BLEND_ALPHA_KEY,
    THREE_BLEND_MODE.BLEND_ALPHA,
    THREE_BLEND_MODE.BLEND_NO_ALPHA_ADD,
    THREE_BLEND_MODE.BLEND_ADD,
    THREE_BLEND_MODE.BLEND_MOD,
    THREE_BLEND_MODE.BLEND_MOD2X,
  ],
  [M2_MATERIAL_PASS.PASS_1]: [
    THREE_BLEND_MODE.BLEND_ALPHA,
    THREE_BLEND_MODE.BLEND_ALPHA,
    THREE_BLEND_MODE.BLEND_ALPHA,
    THREE_BLEND_MODE.BLEND_NO_ALPHA_ADD,
    THREE_BLEND_MODE.BLEND_ADD,
    THREE_BLEND_MODE.BLEND_MOD,
    THREE_BLEND_MODE.BLEND_MOD2X,
  ],
};

export { M2_MATERIAL_PASS, M2_MATERIAL_TO_THREE_BLEND_MODE };
