import { THREE_BLEND } from '../blend.js';

const M2_MATERIAL_BLEND_TO_THREE_BLEND_OPAQUE = [
  THREE_BLEND.BLEND_OPAQUE,
  THREE_BLEND.BLEND_ALPHA_KEY,
  THREE_BLEND.BLEND_ALPHA,
  THREE_BLEND.BLEND_NO_ALPHA_ADD,
  THREE_BLEND.BLEND_ADD,
  THREE_BLEND.BLEND_MOD,
  THREE_BLEND.BLEND_MOD2X,
];

const M2_MATERIAL_BLEND_TO_THREE_BLEND_TRANSPARENT = [
  THREE_BLEND.BLEND_ALPHA,
  THREE_BLEND.BLEND_ALPHA,
  THREE_BLEND.BLEND_ALPHA,
  THREE_BLEND.BLEND_NO_ALPHA_ADD,
  THREE_BLEND.BLEND_ADD,
  THREE_BLEND.BLEND_MOD,
  THREE_BLEND.BLEND_MOD2X,
];

export { M2_MATERIAL_BLEND_TO_THREE_BLEND_OPAQUE, M2_MATERIAL_BLEND_TO_THREE_BLEND_TRANSPARENT };
