enum MODEL_SHADER_VERTEX {
  VERTEX_T1 = 0,
  VERTEX_T2,
  VERTEX_ENV,
  VERTEX_T1_T2,
  VERTEX_T1_ENV,
  VERTEX_ENV_T2,
  VERTEX_ENV_ENV,
  VERTEX_UNKNOWN,
}

enum MODEL_SHADER_FRAGMENT {
  FRAGMENT_OPAQUE = 0,
  FRAGMENT_MOD,
  FRAGMENT_UNKNOWN,
}

export { MODEL_SHADER_FRAGMENT, MODEL_SHADER_VERTEX };
