enum LIGHT_PARAM {
  PARAM_STANDARD = 0,
  PARAM_STANDARD_UNDERWATER,
  PARAM_STORMY,
  PARAM_STORMY_UNDERWATER,
  PARAM_DEATH,
  PARAM_5,
  PARAM_6,
  PARAM_7,
  NUM_LIGHT_PARAMS,
}

enum LIGHT_INT_BAND {
  BAND_DIRECT_COLOR = 0,
  BAND_AMBIENT_COLOR,
  BAND_SKY_TOP_COLOR,
  BAND_SKY_MIDDLE_COLOR,
  BAND_SKY_BAND_1_COLOR,
  BAND_SKY_BAND_2_COLOR,
  BAND_SKY_SMOG_COLOR,
  BAND_SKY_FOG_COLOR,
  BAND_SUN_COLOR,
  BAND_CLOUD_SUN_COLOR,
  BAND_CLOUD_EMISSIVE_COLOR,
  BAND_CLOUD_LAYER_1_AMBIENT_COLOR,
  BAND_CLOUD_LAYER_2_AMBIENT_COLOR,
  BAND_13,
  BAND_OCEAN_CLOSE_COLOR,
  BAND_OCEAN_FAR_COLOR,
  BAND_RIVER_CLOSE_COLOR,
  BAND_RIVER_FAR_COLOR,
  NUM_LIGHT_INT_BANDS,
}

enum LIGHT_FLOAT_BAND {
  BAND_FOG_END,
  BAND_FOG_START_SCALAR,
  BAND_2,
  BAND_3,
  BAND_4,
  BAND_5,
  NUM_LIGHT_FLOAT_BANDS,
}

export { LIGHT_PARAM, LIGHT_INT_BAND, LIGHT_FLOAT_BAND };
